# Generated by Django 5.2.14 on 2026-05-06 06:35

import django.db.models.deletion
import game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=game.models.generate_room_code, max_length=6, unique=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('hard', 'Hard')], default='easy', max_length=4)),
                ('min_players', models.IntegerField(default=2)),
                ('max_players', models.IntegerField(default=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('lives', models.IntegerField(default=3)),
                ('is_host', models.BooleanField(default=False)),
                ('channel_name', models.CharField(blank=True, max_length=255)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.room')),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_syllable', models.CharField(default='', max_length=10)),
                ('current_player_index', models.IntegerField(default=0)),
                ('bomb_timer', models.IntegerField(default=20)),
                ('is_running', models.BooleanField(default=False)),
                ('used_words', models.JSONField(default=list)),
                ('round_number', models.IntegerField(default=1)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='game.room')),
            ],
        ),
    ]
