# Generated by Django 6.0.5 on 2026-05-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='bomb_timer',
            field=models.IntegerField(default=20),
        ),
    ]
